---
- name: Update web, NFS, and DB servers
  hosts: webservers:nfs
  remote_user: ec2-user
  become: yes
  become_user: root
  tasks:
    - name: Delete Wireshark
      yum:
        name: wireshark
        state: removed

    - name: Set timezone to Asia/Tokyo
      command: timedatectl set-timezone Asia/Tokyo

- name: Update DB server
  hosts: db
  remote_user: ubuntu
  become: yes
  become_user: root
  tasks:
    - name: Update apt repo
      apt:
        update_cache: yes

    - name: Delete Wireshark
      apt:
        name: wireshark
        state: absent  # Change 'removed' to 'absent'
        autoremove: yes
        purge: yes
        autoclean: yes
