---
- name: Update web, nfs and db servers
  hosts: webservers:nfs
  become: yes
  tasks:
    - name: Ensure wireshark is at the latest version (web/nfs)
      yum:
        name: wireshark
        state: latest

- name: Update DB server
  hosts: db
  become: yes
  tasks:
    - name: Update apt repo
      apt:
        update_cache: yes

    - name: Ensure wireshark is at the latest version (db)
      apt:
        name: wireshark
        state: latest
